# -*- coding: utf-8 -*-
"""Projeto_Big_Data_Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189_yXqY0WEjogUOvvZuBxyOZ6jdKfvvr

# Dashboard
"""

!pip install -q duckdb plotly pyarrow

import os
import pandas as pd
import duckdb

import plotly.express as px
import plotly.graph_objects as go

from IPython.display import display, HTML

from google.colab import drive

drive.mount('/content/drive')

"""### Configurar diretórios"""

import os

BASE_DIR = "/content/drive/MyDrive/avaliacao_final"

ETAPA2_DIR = os.path.join(
    BASE_DIR,
    "etapa2_bigdata"
)

ETAPA3_DIR = os.path.join(
    BASE_DIR,
    "etapa3_analise"
)

DATA_DIR = os.path.join(
    ETAPA2_DIR,
    "data"
)

GOLD_DIR = os.path.join(
    DATA_DIR,
    "gold"
)

os.makedirs(
    ETAPA3_DIR,
    exist_ok=True
)

print("Etapa 2:", ETAPA2_DIR)
print("Etapa 3:", ETAPA3_DIR)
print("Gold:", GOLD_DIR)

"""### Localizar as tabelas Gold"""

GOLD_CANAL = os.path.join(
    GOLD_DIR,
    "fraude_por_canal.parquet"
)

GOLD_CATEGORIA = os.path.join(
    GOLD_DIR,
    "fraude_por_categoria.parquet"
)

GOLD_SEGMENTO = os.path.join(
    GOLD_DIR,
    "fraude_por_segmento.parquet"
)

GOLD_PERIODO = os.path.join(
    GOLD_DIR,
    "fraude_por_periodo.parquet"
)

for arquivo in [
    GOLD_CANAL,
    GOLD_CATEGORIA,
    GOLD_SEGMENTO,
    GOLD_PERIODO
]:

    print(
        "OK:" if os.path.exists(arquivo)
        else "ERRO:",
        arquivo
    )

"""### Ler Tabelas Gold"""

import pandas as pd

df_canal = pd.read_parquet(
    GOLD_CANAL
)

df_categoria = pd.read_parquet(
    GOLD_CATEGORIA
)

df_segmento = pd.read_parquet(
    GOLD_SEGMENTO
)

df_periodo = pd.read_parquet(
    GOLD_PERIODO
)

print("Gold carregada com sucesso.")

print("\nCanal:")
display(df_canal)

print("\nCategoria:")
display(df_categoria)

print("\nSegmento:")
display(df_segmento)

print("\nPeríodo:")
display(df_periodo)

"""### Calcular os KPIs gerais"""

# Total de transações
total_transacoes = df_canal[
    "total_transacoes"
].sum()

# Total de fraudes
total_fraudes = df_canal[
    "transacoes_fraudulentas"
].sum()

# Valor total das transações
valor_total = df_canal[
    "valor_total"
].sum()

# Valor associado às fraudes
valor_fraudado = df_canal[
    "valor_fraudado"
].sum()

# Taxa geral de fraude
taxa_fraude = (
    total_fraudes /
    total_transacoes
)

print(
    f"Total de transações: {total_transacoes:.0f}"
)

print(
    f"Total de fraudes: {total_fraudes:,.0f}"
)

print(
    f"Taxa de fraude: {taxa_fraude:.2%}"
)

print(
    f"Valor total: R$ {valor_total:.2f}"
)

print(
    f"Valor fraudado: R$ {valor_fraudado:.2f}"
)

"""### Canal de maior risco"""

canal_maior_risco = df_canal.loc[
    df_canal["taxa_fraude"].idxmax()
]

print(
    "Canal com maior taxa de fraude:"
)

print(
    canal_maior_risco["channel"]
)

print(
    f"Taxa de fraude: "
    f"{canal_maior_risco['taxa_fraude']:.2%}"
)

"""### Categoria de maior risco"""

categoria_maior_risco = df_categoria.loc[
    df_categoria["taxa_fraude"].idxmax()
]

print(
    "Categoria com maior taxa de fraude:"
)

print(
    categoria_maior_risco[
        "merchant_category"
    ]
)

print(
    f"Taxa de fraude: "
    f"{categoria_maior_risco['taxa_fraude']:.2%}"
)

"""### Análise por segmento"""

df_segmento_ordenado = (
    df_segmento
    .sort_values(
        "taxa_fraude",
        ascending=False
    )
)

display(df_segmento_ordenado)

segmento_maior_risco = (
    df_segmento_ordenado.iloc[0]
)

print(
    "Segmento com maior taxa de fraude:"
)

print(
    segmento_maior_risco["segment"]
)

print(
    f"Taxa de fraude: "
    f"{segmento_maior_risco['taxa_fraude']:.2%}"
)

"""### Análise temporal"""

df_periodo = df_periodo.sort_values(
    ["ano", "mes"]
)

df_periodo["periodo"] = (
    df_periodo["ano"].astype(str)
    + "-"
    + df_periodo["mes"].astype(str).str.zfill(2)
)

display(df_periodo)

"""### Maior taxa mensal"""

periodo_maior_risco = df_periodo.loc[
    df_periodo["taxa_fraude"].idxmax()
]

print(
    "Período com maior taxa de fraude:"
)

print(
    periodo_maior_risco["periodo"]
)

print(
    f"Taxa de fraude: "
    f"{periodo_maior_risco['taxa_fraude']:.2%}"
)

"""### Gráfico de tendência"""

import plotly.graph_objects as go

fig_tendencia = go.Figure()

fig_tendencia.add_trace(
    go.Scatter(
        x=df_periodo["periodo"],
        y=df_periodo["taxa_fraude"] * 100,
        mode="lines+markers",
        name="Taxa de fraude"
    )
)

fig_tendencia.update_layout(
    title="Evolução da Taxa de Fraude",
    xaxis_title="Período",
    yaxis_title="Taxa de fraude (%)",
    template="plotly_white"
)

fig_tendencia.show()

"""### Gráfico de fraude por canal"""

fig_canal = go.Figure()

fig_canal.add_trace(
    go.Bar(
        x=df_canal["channel"],
        y=df_canal["taxa_fraude"] * 100,
        text=(
            df_canal["taxa_fraude"] * 100
        ).round(2),
        texttemplate="%{text}%",
        textposition="outside"
    )
)

fig_canal.update_layout(
    title="Taxa de Fraude por Canal",
    xaxis_title="Canal",
    yaxis_title="Taxa de fraude (%)",
    template="plotly_white"
)

fig_canal.show()

"""### Gráfico de fraude por categoria"""

df_categoria_plot = (
    df_categoria
    .sort_values(
        "taxa_fraude",
        ascending=True
    )
)

fig_categoria = go.Figure()

fig_categoria.add_trace(
    go.Bar(
        x=df_categoria_plot["taxa_fraude"] * 100,
        y=df_categoria_plot[
            "merchant_category"
        ],
        orientation="h",
        text=(
            df_categoria_plot[
                "taxa_fraude"
            ] * 100
        ).round(2),
        texttemplate="%{text}%",
        textposition="outside"
    )
)

fig_categoria.update_layout(
    title="Taxa de Fraude por Categoria",
    xaxis_title="Taxa de fraude (%)",
    yaxis_title="Categoria",
    template="plotly_white"
)

fig_categoria.show()

"""### Criar tabela de detalhe"""

df_detalhe = df_canal.copy()

df_detalhe["taxa_fraude"] = (
    df_detalhe["taxa_fraude"] * 100
).round(2)

df_detalhe["valor_total"] = (
    df_detalhe["valor_total"]
).round(2)

df_detalhe["valor_fraudado"] = (
    df_detalhe["valor_fraudado"]
).round(2)

display(df_detalhe)

"""### Criar os KPIs do dashboard"""

# Formatação padrão BR
def formatar_numero_br(valor, casas=0):
    return f"{valor:,.{casas}f}".replace(",", "X").replace(".", ",").replace("X", ".")


# Valores formatados
total_transacoes_br = formatar_numero_br(total_transacoes)
total_fraudes_br = formatar_numero_br(total_fraudes)
taxa_fraude_br = formatar_numero_br(taxa_fraude * 100, 2)
valor_fraudado_br = formatar_numero_br(valor_fraudado, 2)


fig_kpis = go.Figure()

fig_kpis.add_trace(
    go.Indicator(
        mode="number",
        value=total_transacoes,
        title={"text": "Transações"},
        number={
            "valueformat": ",.0f"
        },
        domain={
            "row": 0,
            "column": 0
        }
    )
)

fig_kpis.add_trace(
    go.Indicator(
        mode="number",
        value=total_fraudes,
        title={"text": "Fraudes"},
        number={
            "valueformat": ",.0f"
        },
        domain={
            "row": 0,
            "column": 1
        }
    )
)

fig_kpis.add_trace(
    go.Indicator(
        mode="number",
        value=taxa_fraude * 100,
        title={"text": "Taxa de fraude (%)"},
        number={
            "suffix": "%",
            "valueformat": ".2f"
        },
        domain={
            "row": 0,
            "column": 2
        }
    )
)

fig_kpis.add_trace(
    go.Indicator(
        mode="number",
        value=valor_fraudado,
        title={"text": "Valor fraudado (R$)"},
        number={
            "prefix": "R$ ",
            "valueformat": ",.2f"
        },
        domain={
            "row": 0,
            "column": 3
        }
    )
)

fig_kpis.update_layout(
    grid={
        "rows": 1,
        "columns": 4
    },
    height=220,
    template="plotly_white",
    separators=",."
)

fig_kpis.show()

"""### Dashboard completo"""

from plotly.subplots import make_subplots

dashboard = make_subplots(

    rows=4,
    cols=4,

    specs=[

        # ==================================================
        # LINHA 1 — 4 KPIs LADO A LADO
        # ==================================================

        [
            {"type": "indicator"},
            {"type": "indicator"},
            {"type": "indicator"},
            {"type": "indicator"}
        ],

        # ==================================================
        # LINHA 2 — 2 GRÁFICOS
        # Cada gráfico ocupa 2 colunas
        # ==================================================

        [
            {"type": "xy", "colspan": 2},
            None,
            {"type": "xy", "colspan": 2},
            None
        ],

        # ==================================================
        # LINHA 3 — 2 GRÁFICOS
        # ==================================================

        [
            {"type": "xy", "colspan": 2},
            None,
            {"type": "xy", "colspan": 2},
            None
        ],

        # ==================================================
        # LINHA 4 — TABELA
        # ==================================================

        [
            {"type": "table", "colspan": 4},
            None,
            None,
            None
        ]
    ],

    subplot_titles=[

        # KPIs
        "",
        "",
        "",
        "",

        # Linha 2
        "Evolução da Taxa de Fraude",
        "Taxa de Fraude por Canal",

        # Linha 3
        "Taxa de Fraude por Categoria",
        "Taxa de Fraude por Segmento",

        # Linha 4
        "Detalhamento das Transações"
    ],

    vertical_spacing=0.08,

    horizontal_spacing=0.04
)

"""### Adicionar os KPIs"""

# ============================================================
# INSERÇÃO DOS 4 KPIs NO DASHBOARD
# ============================================================

# KPI 1 — Total de Transações
dashboard.add_trace(
    go.Indicator(
        mode="number",
        value= total_transacoes,
        title={"text": "Total de Transações",
        "font": {"size": 30}

        },
        number={
            "valueformat": ",.0f",
            "font": {"size": 52}
        }
    ),
    row=1,
    col=1
)


# KPI 2 — Total de Fraudes
dashboard.add_trace(
    go.Indicator(
        mode="number",
        value=total_fraudes,
        title={"text": "Total de Fraudes",
        "font": {"size": 30}

        },
        number={
            "valueformat": ",.0f",
            "font": {"size": 52}
        }
    ),
    row=1,
    col=2
)


# KPI 3 — Taxa de Fraude
dashboard.add_trace(
    go.Indicator(
        mode="number",
        value=taxa_fraude * 100,
        title={"text": "Taxa de Fraude",
        "font": {"size": 30}

        },
        number={
            "suffix": "%",
            "valueformat": ".2f",
            "font": {"size": 52}
        }
    ),
    row=1,
    col=3
)


# KPI 4 — Valor Fraudado
dashboard.add_trace(
    go.Indicator(
        mode="number",
        value=valor_fraudado,
        title={"text": "Valor Fraudado",
        "font": {"size": 30}

        },
        number={
            "prefix": "R$ ",
            "valueformat": ",.2f",
            "font": {"size": 52}
        }
    ),
    row=1,
    col=4
)

"""### Adicionar tendência"""

# ============================================================
# GRÁFICO — EVOLUÇÃO DA TAXA DE FRAUDE
# ============================================================

dashboard.add_trace(

    go.Scatter(
        x=df_periodo["periodo"],
        y=df_periodo["taxa_fraude"] * 100,
        mode="lines+markers",
        name="Taxa de fraude",
        hovertemplate=
            "Período: %{x}<br>" +
            "Taxa de fraude: %{y:.2f}%<extra></extra>"
    ),

    row=2,
    col=1
)

dashboard.add_trace(

    go.Scatter(
        x=df_periodo["periodo"],
        y=df_periodo["taxa_fraude"] * 100,

        mode="lines+markers+text",

        name="Taxa de fraude",

        # Valor exibido em cada ponto
        text=(df_periodo["taxa_fraude"] * 100).map(
            lambda x: f"{x:.2f}%"
        ),

        textposition="top center",

        # Formatação do texto ao passar o mouse
        hovertemplate=
            "Período: %{x}<br>" +
            "Taxa de fraude: %{y:.2f}%<extra></extra>"
    ),

    row=2,
    col=1
)

"""### Adicionar canal"""

# Taxa por Canal
dashboard.add_trace(
    go.Bar(
        x=df_canal["channel"],
        y=df_canal["taxa_fraude"] * 100,
        name="Canal",

        # Valor visível
        text=(df_canal["taxa_fraude"] * 100).apply(
            lambda x: f"{x:.2f}%".replace(".", ",")
        ),
        textposition="outside"
    ),
    row=2,
    col=3
)

"""### Adicionar categoria"""

dashboard.add_trace(
    go.Bar(
        x=df_categoria_plot["taxa_fraude"] * 100,
        y=df_categoria_plot["merchant_category"],
        orientation="h",
        name="Categoria",
        marker_color="#2ca02c",

        # Valor visível nas barras
        text=(df_categoria_plot["taxa_fraude"] * 100).apply(
            lambda x: f"{x:.2f}%".replace(".", ",")
        ),
        textposition="outside"
    ),
    row=3,
    col=1
)

"""### Adicionar segmento"""

dashboard.add_trace(
    go.Bar(
        x=df_segmento_ordenado["taxa_fraude"] * 100,
        y=df_segmento_ordenado["segment"],
        orientation="h",
        name="Segmento",
        marker_color="#FF7F0E",
        text=round(
            df_segmento_ordenado["taxa_fraude"] * 100,
            2
        ),
        texttemplate="%{text:.2f}%",
        textposition="outside"
    ),
    row=3,
    col=3
)

"""### Adicionando tabela das transações"""

dashboard.add_trace(
    go.Table(
        header=dict(
            values=[
                "Canal",
                "Transações",
                "Fraudes",
                "Taxa de fraude",
                "Valor fraudado"
            ]
        ),

        cells=dict(
            values=[
                df_detalhe["channel"],
                df_detalhe["total_transacoes"],
                df_detalhe["transacoes_fraudulentas"],
                df_detalhe["taxa_fraude"].astype(str) + "%",
                df_detalhe["valor_fraudado"].apply(
                    lambda x: f"R$ {x:,.2f}"
                )
            ]
        )
    ),
    row=4,
    col=1
)

"""### Adicionar detalhe"""

dashboard.add_trace(
    go.Table(
        header=dict(
            values=[
                "Canal",
                "Transações",
                "Fraudes",
                "Taxa de Fraude (%)",
                "Valor Fraudado (R$)"
            ],
            fill_color="#1F4E79",
            font=dict(color="white", size=12),
            align="center",
            height=35
        ),

        cells=dict(
            values=[
                # Canal
                df_detalhe["channel"],

                # Transações → 1.234.567
                df_detalhe["total_transacoes"]
                    .apply(lambda x: f"{x:,.0f}".replace(",", "X").replace(".", ",").replace("X", ".")),

                # Fraudes → 12.345
                df_detalhe["transacoes_fraudulentas"]
                    .apply(lambda x: f"{x:,.0f}".replace(",", "X").replace(".", ",").replace("X", ".")),

                # Taxa → 1,25%
                df_detalhe["taxa_fraude"]
                    .apply(lambda x: f"{x:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".") + "%"),

                # Valor → R$ 1.234.567,89
                df_detalhe["valor_fraudado"]
                    .apply(lambda x: f"R$ {x:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."))
            ],

            align=[
                "left",
                "center",
                "center",
                "center",
                "right"
            ],

            height=28
        )
    ),
    row=4,
    col=1
)

"""### Configurar aparência do dashboard"""

dashboard.update_layout(
    title=dict(
        text="TechPay - Dashboard de Risco e Fraude",
        x=0.5,
        xanchor="center",
        font=dict(
            size=36,
            color="#1F2937"
        )
    ),

    height=1500,

    separators=",.",

    template="plotly_white",

    showlegend=False,

    margin=dict(
        l=50,
        r=50,
        t=100,
        b=50
    )
)

# ==================================================
# Evolução da Taxa de Fraude
# ==================================================

dashboard.update_xaxes(
    title_text="Período",
    row=2,
    col=1
)

dashboard.update_yaxes(
    title_text="Taxa de Fraude (%)",
    row=2,
    col=1
)

# ==================================================
# Taxa de Fraude por Canal
# ==================================================

dashboard.update_xaxes(
    title_text="Canal",
    row=2,
    col=3
)

dashboard.update_yaxes(
    title_text="Taxa de Fraude (%)",
    row=2,
    col=3
)

# ==================================================
# Taxa de Fraude por Categoria
# ==================================================

dashboard.update_xaxes(
    title_text="Taxa de Fraude (%)",
    row=3,
    col=1
)

dashboard.update_yaxes(
    title_text="Categoria",
    row=3,
    col=1
)

# ==================================================
# Taxa de Fraude por Segmento
# ==================================================

dashboard.update_xaxes(
    title_text="Taxa de Fraude (%)",
    row=3,
    col=3
)

dashboard.update_yaxes(
    title_text="Segmento",
    row=3,
    col=3
)

dashboard.show()

"""### Exportar o dashboard para HTML"""

DASHBOARD_PATH = os.path.join(
    ETAPA3_DIR,
    "dashboard_techpay.html"
)

dashboard.write_html(
    DASHBOARD_PATH,
    include_plotlyjs=True
)

print(
    "Dashboard criado com sucesso!"
)

print(
    DASHBOARD_PATH
)

"""### Gerar os achados automaticamente"""

print("=" * 70)
print("ACHADOS DA ANÁLISE")
print("=" * 70)

print("\n1. CANAL")
print(
    f"Finding: o canal "
    f"'{canal_maior_risco['channel']}' "
    f"apresentou a maior taxa de fraude, "
    f"de {canal_maior_risco['taxa_fraude']:.2%}."
)

print(
    "\nInsight: esse resultado indica que "
    "esse canal merece atenção prioritária "
    "na estratégia de monitoramento de risco."
)

print(
    "\nAção: recomenda-se avaliar regras de "
    "detecção e monitoramento específicas "
    "para esse canal."
)


print("\n" + "-" * 70)

print("\n2. CATEGORIA")

print(
    f"Finding: a categoria "
    f"'{categoria_maior_risco['merchant_category']}' "
    f"apresentou a maior taxa de fraude, "
    f"de {categoria_maior_risco['taxa_fraude']:.2%}."
)

print(
    "\nInsight: existe concentração de risco "
    "nessa categoria de estabelecimento."
)

print(
    "\nAção: a área de risco pode priorizar "
    "o monitoramento das transações dessa categoria."
)


print("\n" + "-" * 70)

print("\n3. SEGMENTO")

print(
    f"Finding: o segmento "
    f"'{segmento_maior_risco['segment']}' "
    f"apresentou a maior taxa de fraude, "
    f"de {segmento_maior_risco['taxa_fraude']:.2%}."
)

print(
    "\nInsight: o comportamento de fraude "
    "não é uniforme entre os segmentos."
)

print(
    "\nAção: recomenda-se utilizar o segmento "
    "como uma das dimensões de priorização "
    "da análise de risco."
)


print("\n" + "-" * 70)

print("\n4. TEMPO")

print(
    f"Finding: o período "
    f"'{periodo_maior_risco['periodo']}' "
    f"apresentou a maior taxa de fraude, "
    f"de {periodo_maior_risco['taxa_fraude']:.2%}."
)

print(
    "\nInsight: o risco apresenta variação "
    "ao longo do tempo."
)

print(
    "\nAção: a área de risco pode reforçar "
    "o monitoramento durante períodos "
    "com maior incidência."
)

"""### Pergunta própria

Valores mais altos de trasações apresentam maior concentração de fraude?
"""

SILVER_PATH = os.path.join(
    DATA_DIR,
    "silver",
    "transactions_silver.parquet"
)

silver = pd.read_parquet(
    SILVER_PATH
)

print(
    f"Silver carregada: "
    f"{len(silver):,} registros"
)

"""### Analisar fraude por faixa de valor"""

analise_valor = (
    silver
    .groupby("faixa_valor", observed=True)
    .agg(
        total_transacoes=(
            "transaction_id",
            "count"
        ),

        fraudes=(
            "is_fraud",
            "sum"
        ),

        valor_fraudado=(
            "amount",
            lambda x: x[
                silver.loc[
                    x.index,
                    "is_fraud"
                ] == True
            ].sum()
        )
    )
    .reset_index()
)

analise_valor["taxa_fraude"] = (
    analise_valor["fraudes"]
    / analise_valor["total_transacoes"]
)

display(
    analise_valor
)

"""### Encontrar faixa de maior risco"""

faixa_maior_risco = (
    analise_valor.loc[
        analise_valor["taxa_fraude"].idxmax()
    ]
)

print(
    "Faixa de valor com maior taxa de fraude:"
)

print(
    faixa_maior_risco["faixa_valor"]
)

print(
    f"Taxa de fraude: "
    f"{faixa_maior_risco['taxa_fraude']:.2%}"
)

"""### Gráfico faixa de maior risco"""

fig_valor = go.Figure()

fig_valor.add_trace(
    go.Bar(
        x=analise_valor[
            "faixa_valor"
        ].astype(str),

        y=analise_valor[
            "taxa_fraude"
        ] * 100,

        text=(
            analise_valor[
                "taxa_fraude"
            ] * 100
        ).round(2),

        texttemplate="%{text}%",

        textposition="outside"
    )
)

fig_valor.update_layout(
    title=(
        "Taxa de Fraude por Faixa de Valor"
    ),

    xaxis_title="Faixa de valor",

    yaxis_title="Taxa de fraude (%)",

    template="plotly_white"
)

fig_valor.show()

"""### Análise faixa de maior risco"""

analise_valor_path = os.path.join(
    ETAPA3_DIR,
    "analise_fraude_por_faixa_valor.csv"
)

analise_valor.to_csv(
    analise_valor_path,
    index=False,
    encoding="utf-8-sig"
)

print(
    "Análise salva em:"
)

print(
    analise_valor_path
)

