# -*- coding: utf-8 -*-
"""Projeto_Big_Data_Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBdULCpLhMEqwxnTX0vnBMLd_B2jX46R

### Instalação das bibliotecas
"""

!pip install -q duckdb pyarrow
!pip install -q pyspark

import pyspark

print("PySpark:", pyspark.__version__)

"""### Google Drive"""

from google.colab import drive

drive.mount('/content/drive')

"""### Definir a estrutura do projeto"""

import os

BASE_DIR = "/content/drive/MyDrive/avaliacao_final/etapa2_bigdata"

DATA_DIR = os.path.join(BASE_DIR, "data")

RAW_DIR = os.path.join(DATA_DIR, "raw")
BRONZE_DIR = os.path.join(DATA_DIR, "bronze")
SILVER_DIR = os.path.join(DATA_DIR, "silver")
GOLD_DIR = os.path.join(DATA_DIR, "gold")

for diretorio in [
    RAW_DIR,
    BRONZE_DIR,
    SILVER_DIR,
    GOLD_DIR
]:
    os.makedirs(diretorio, exist_ok=True)

print("Estrutura criada com sucesso.")
print()
print("Projeto:", BASE_DIR)
print("RAW:", RAW_DIR)
print("BRONZE:", BRONZE_DIR)
print("SILVER:", SILVER_DIR)
print("GOLD:", GOLD_DIR)

"""Colocar o arquivo avaliacao_transactions.csv na pasta raw.

Seguir o caminho /content/drive/MyDrive/avaliacao_final/etapa2_bigdata/data/raw do seu drive e colocar o arquivo avaliacao_transactions.csv na pasta.

### Localizar o CSV
"""

CSV_PATH = os.path.join(
    RAW_DIR,
    "avaliacao_transactions.csv"
)

if os.path.exists(CSV_PATH):
    print("Arquivo encontrado!")
    print(CSV_PATH)
else:
    print("ERRO: arquivo não encontrado.")
    print()
    print("Coloque avaliacao_transactions.csv em:")
    print(RAW_DIR)

"""## ETAPA 1: INGESTÃO"""

import pandas as pd

print("=" * 70)
print("ETAPA 1 — INGESTÃO")
print("=" * 70)

df_raw = pd.read_csv(CSV_PATH)

print(f"Quantidade de linhas: {len(df_raw):,}")
print(f"Quantidade de colunas: {len(df_raw.columns)}")

print("\nColunas:")
print(df_raw.columns.tolist())

print("\nPrimeiras 5 linhas:")
display(df_raw.head())

"""### Diagnóstico inicial"""

print("=" * 70)
print("DIAGNÓSTICO INICIAL")
print("=" * 70)

display(df_raw.info())

print("\nValores ausentes:")
display(df_raw.isna().sum())

print("\nDuplicidades completas:")
print(df_raw.duplicated().sum())

print("\nEstatísticas numéricas:")

display(
    df_raw[
        [
            "amount",
            "risk_score",
            "credit_score"
        ]
    ].describe()
)

"""### ETAPA 2: CRIAÇÃO DA RAW"""

print("=" * 70)
print("ETAPA 2 — RAW")
print("=" * 70)

df = df_raw.copy()

# Padronização dos nomes
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
)

# IDs
df["transaction_id"] = pd.to_numeric(
    df["transaction_id"],
    errors="coerce"
).astype("Int64")

df["customer_id"] = pd.to_numeric(
    df["customer_id"],
    errors="coerce"
).astype("Int64")

# Valores numéricos
df["amount"] = pd.to_numeric(
    df["amount"],
    errors="coerce"
)

df["risk_score"] = pd.to_numeric(
    df["risk_score"],
    errors="coerce"
)

df["credit_score"] = pd.to_numeric(
    df["credit_score"],
    errors="coerce"
).astype("Int64")

# Data
df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    errors="coerce"
)

# Variáveis categóricas
colunas_categoricas = [
    "transaction_type",
    "channel",
    "merchant_category",
    "status",
    "segment"
]

for coluna in colunas_categoricas:

    df[coluna] = (
        df[coluna]
        .astype("string")
        .str.strip()
        .str.lower()
    )

# Variável de fraude
df["is_fraud"] = (
    df["is_fraud"]
    .astype("string")
    .str.lower()
    .map({
        "true": True,
        "false": False,
        "1": True,
        "0": False,
        "yes": True,
        "no": False
    })
)

print("Tipos definidos:")
display(
    pd.DataFrame({
        "coluna": df.columns,
        "tipo": df.dtypes.astype(str)
    })
)

"""### Salvar RAW"""

RAW_PARQUET = os.path.join(
    RAW_DIR,
    "transactions_raw.parquet"
)

df.to_parquet(
    RAW_PARQUET,
    index=False
)

print("RAW salva com sucesso:")
print(RAW_PARQUET)

print()
print(f"Linhas na RAW: {len(df):,}")

"""### ETAPA 3: PARTICIONAMENTO"""

print("=" * 70)
print("ETAPA 3 — PARTICIONAMENTO")
print("=" * 70)

df["ano"] = df["timestamp"].dt.year
df["mes"] = df["timestamp"].dt.month

print("Colunas utilizadas para particionamento:")
print("ano")
print("mes")

print("\nDistribuição temporal:")

display(
    df.groupby(
        ["ano", "mes"]
    ).size().reset_index(
        name="quantidade_transacoes"
    )
)

print(
    "Quantidade de partições:",
    df[["ano", "mes"]].drop_duplicates().shape[0]
)

"""## ETAPA 4: BRONZE — Limpeza"""

print("=" * 70)
print("ETAPA 4 — BRONZE")
print("=" * 70)

linhas_inicial_bronze = len(df)

print(
    f"Linhas antes da limpeza: "
    f"{linhas_inicial_bronze:,}"
)

"""### Duplicidades"""

duplicidades_id = df["transaction_id"].duplicated().sum()

print(
    f"Duplicidades de transaction_id: "
    f"{duplicidades_id:,}"
)

df = df.drop_duplicates(
    subset=["transaction_id"],
    keep="first"
)

"""### IDs inválidos"""

ids_invalidos = (
    df["transaction_id"].isna()
).sum()

clientes_invalidos = (
    df["customer_id"].isna()
).sum()

print(
    f"transaction_id ausente: "
    f"{ids_invalidos:,}"
)

print(
    f"customer_id ausente: "
    f"{clientes_invalidos:,}"
)

df = df[
    df["transaction_id"].notna()
    & df["customer_id"].notna()
]

"""### Valores Financeiros"""

valores_negativos = (
    df["amount"] < 0
).sum()

print(
    f"Valores negativos encontrados: "
    f"{valores_negativos:,}"
)

df = df[
    df["amount"].notna()
    & (df["amount"] >= 0)
]

"""### Risk score"""

risk_invalidos = (
    ~df["risk_score"].between(0, 100)
    & df["risk_score"].notna()
).sum()

print(
    f"Risk scores inválidos: "
    f"{risk_invalidos:,}"
)

df = df[
    df["risk_score"].between(0, 100)
    | df["risk_score"].isna()
]

"""### Credit score"""

credit_invalidos = (
    ~df["credit_score"].between(300, 900)
    & df["credit_score"].notna()
).sum()

print(
    f"Credit scores inválidos: "
    f"{credit_invalidos:,}"
)

df = df[
    df["credit_score"].between(300, 900)
    | df["credit_score"].isna()
]

"""### timestamp"""

datas_invalidas = df["timestamp"].isna().sum()

print(
    f"Datas inválidas ou ausentes: "
    f"{datas_invalidas:,}"
)

df = df[
    df["timestamp"].notna()
]

"""### Verificar categorias"""

for coluna in [
    "transaction_type",
    "channel",
    "merchant_category",
    "status",
    "segment"
]:

    print("\n" + coluna)

    display(
        df[coluna]
        .value_counts(dropna=False)
        .to_frame("quantidade")
    )

"""### Resultado da Bronze"""

linhas_final_bronze = len(df)

linhas_descartadas = (
    linhas_inicial_bronze
    - linhas_final_bronze
)

print("=" * 70)
print("RESULTADO DA BRONZE")
print("=" * 70)

print(
    f"Linhas antes:       {linhas_inicial_bronze:,}"
)

print(
    f"Linhas depois:      {linhas_final_bronze:,}"
)

print(
    f"Linhas descartadas: {linhas_descartadas:,}"
)

"""### Salvar Bronze particionada"""

# Limpar diretório anterior da Bronze, se necessário
import shutil

if os.path.exists(BRONZE_DIR):
    shutil.rmtree(BRONZE_DIR)

os.makedirs(BRONZE_DIR, exist_ok=True)

df.to_parquet(
    BRONZE_DIR,
    engine="pyarrow",
    partition_cols=["ano", "mes"],
    index=False
)

print("Bronze particionada salva em:")
print(BRONZE_DIR)

"""## SILVER"""

print("=" * 70)
print("ETAPA 5 — SILVER")
print("=" * 70)

silver = df.copy()

print(
    f"Linhas recebidas da Bronze: "
    f"{len(silver):,}"
)

"""### Silver: faixa de valor"""

silver["faixa_valor"] = pd.cut(
    silver["amount"],
    bins=[
        -float("inf"),
        100,
        500,
        1000,
        5000,
        float("inf")
    ],
    labels=[
        "Até R$ 100",
        "R$ 100 a R$ 500",
        "R$ 500 a R$ 1.000",
        "R$ 1.000 a R$ 5.000",
        "Acima de R$ 5.000"
    ]
)

display(
    silver["faixa_valor"]
    .value_counts()
    .sort_index()
    .to_frame("quantidade")
)

"""### Silver: período do dia"""

def classificar_periodo(hora):

    if 6 <= hora < 12:
        return "manhã"

    elif 12 <= hora < 18:
        return "tarde"

    elif 18 <= hora < 24:
        return "noite"

    else:
        return "madrugada"


silver["periodo_dia"] = (
    silver["timestamp"]
    .dt.hour
    .apply(classificar_periodo)
)

display(
    silver["periodo_dia"]
    .value_counts()
    .to_frame("quantidade")
)

"""### Silver: dia da semana"""

silver["dia_semana"] = (
    silver["timestamp"]
    .dt.day_name()
)

silver["fim_de_semana"] = (
    silver["timestamp"]
    .dt.dayofweek >= 5
)

display(
    silver[
        [
            "timestamp",
            "dia_semana",
            "fim_de_semana"
        ]
    ].head()
)

"""### Silver: manter channel e merchant_category"""

print("channel:")
display(
    silver["channel"]
    .value_counts(dropna=False)
    .to_frame("quantidade")
)

print("\nmerchant_category:")
display(
    silver["merchant_category"]
    .value_counts(dropna=False)
    .to_frame("quantidade")
)

"""Silver: indicador de fim de semana"""

display(
    silver["fim_de_semana"]
    .value_counts()
    .to_frame("quantidade")
)

"""### Resultado da Silver"""

linhas_silver = len(silver)

print("=" * 70)
print("RESULTADO DA SILVER")
print("=" * 70)

print(
    f"Linhas na Bronze: {linhas_final_bronze:,}"
)

print(
    f"Linhas na Silver: {linhas_silver:,}"
)

print(
    f"Colunas na Silver: {len(silver.columns)}"
)

print("\nColunas adicionais criadas:")

for coluna in [
    "faixa_valor",
    "periodo_dia",
    "dia_semana",
    "fim_de_semana"
]:
    print("•", coluna)

"""### Salvar Silver"""

SILVER_PATH = os.path.join(
    SILVER_DIR,
    "transactions_silver.parquet"
)

silver.to_parquet(
    SILVER_PATH,
    index=False
)

print("Silver salva em:")
print(SILVER_PATH)

"""## GOLD

### Gold — Fraude por canal
"""

print("=" * 70)
print("GOLD 1 — FRAUDE POR CANAL")
print("=" * 70)

gold_canal = (
    silver
    .groupby("channel", dropna=False)
    .agg(
        total_transacoes=(
            "transaction_id",
            "count"
        ),

        transacoes_fraudulentas=(
            "is_fraud",
            "sum"
        ),

        valor_total=(
            "amount",
            "sum"
        ),

        valor_fraudado=(
            "amount",
            lambda x: x[
                silver.loc[
                    x.index,
                    "is_fraud"
                ] == True
            ].sum()
        ),

        risk_score_medio=(
            "risk_score",
            "mean"
        )
    )
    .reset_index()
)

gold_canal["taxa_fraude"] = (
    gold_canal["transacoes_fraudulentas"]
    / gold_canal["total_transacoes"]
)

gold_canal = gold_canal.sort_values(
    "taxa_fraude",
    ascending=False
)

display(gold_canal)

"""### Salvar Gold por canal"""

GOLD_CANAL_PATH = os.path.join(
    GOLD_DIR,
    "fraude_por_canal.parquet"
)

gold_canal.to_parquet(
    GOLD_CANAL_PATH,
    index=False
)

print("Gold por canal salva.")

"""### Gold: fraude por categoria"""

print("=" * 70)
print("GOLD 2 — FRAUDE POR CATEGORIA")
print("=" * 70)

gold_categoria = (
    silver
    .groupby(
        "merchant_category",
        dropna=False
    )
    .agg(
        total_transacoes=(
            "transaction_id",
            "count"
        ),

        transacoes_fraudulentas=(
            "is_fraud",
            "sum"
        ),

        valor_total=(
            "amount",
            "sum"
        ),

        valor_fraudado=(
            "amount",
            lambda x: x[
                silver.loc[
                    x.index,
                    "is_fraud"
                ] == True
            ].sum()
        ),

        risk_score_medio=(
            "risk_score",
            "mean"
        )
    )
    .reset_index()
)

gold_categoria["taxa_fraude"] = (
    gold_categoria["transacoes_fraudulentas"]
    / gold_categoria["total_transacoes"]
)

gold_categoria = gold_categoria.sort_values(
    "taxa_fraude",
    ascending=False
)

display(gold_categoria)

"""### Salvar gold por categoria"""

GOLD_CATEGORIA_PATH = os.path.join(
    GOLD_DIR,
    "fraude_por_categoria.parquet"
)

gold_categoria.to_parquet(
    GOLD_CATEGORIA_PATH,
    index=False
)

print("Gold por categoria salva.")

"""### Gold: fraude por segmento"""

print("=" * 70)
print("GOLD 3 — FRAUDE POR SEGMENTO")
print("=" * 70)

gold_segmento = (
    silver
    .groupby(
        "segment",
        dropna=False
    )
    .agg(
        total_transacoes=(
            "transaction_id",
            "count"
        ),

        transacoes_fraudulentas=(
            "is_fraud",
            "sum"
        ),

        valor_fraudado=(
            "amount",
            lambda x: x[
                silver.loc[
                    x.index,
                    "is_fraud"
                ] == True
            ].sum()
        )
    )
    .reset_index()
)

gold_segmento["taxa_fraude"] = (
    gold_segmento["transacoes_fraudulentas"]
    / gold_segmento["total_transacoes"]
)

gold_segmento = gold_segmento.sort_values(
    "taxa_fraude",
    ascending=False
)

display(gold_segmento)

"""### Evolução Temporal"""

print("=" * 70)
print("GOLD 4 — FRAUDE POR PERÍODO")
print("=" * 70)

gold_periodo = (
    silver
    .groupby(
        ["ano", "mes"],
        dropna=False
    )
    .agg(
        total_transacoes=(
            "transaction_id",
            "count"
        ),

        transacoes_fraudulentas=(
            "is_fraud",
            "sum"
        ),

        valor_total=(
            "amount",
            "sum"
        ),

        valor_fraudado=(
            "amount",
            lambda x: x[
                silver.loc[
                    x.index,
                    "is_fraud"
                ] == True
            ].sum()
        )
    )
    .reset_index()
)

gold_periodo["taxa_fraude"] = (
    gold_periodo["transacoes_fraudulentas"]
    / gold_periodo["total_transacoes"]
)

display(gold_periodo)

"""### Salvar todas as Gold"""

gold_segmento_path = os.path.join(
    GOLD_DIR,
    "fraude_por_segmento.parquet"
)

gold_periodo_path = os.path.join(
    GOLD_DIR,
    "fraude_por_periodo.parquet"
)

gold_segmento.to_parquet(
    gold_segmento_path,
    index=False
)

gold_periodo.to_parquet(
    gold_periodo_path,
    index=False
)

print("Todas as tabelas Gold foram salvas.")

"""### SERVING com DuckDB"""

import duckdb

DUCKDB_PATH = os.path.join(
    DATA_DIR,
    "techpay.duckdb"
)

con = duckdb.connect(DUCKDB_PATH)

print("DuckDB conectado:")
print(DUCKDB_PATH)

"""### Criar tabelas no DuckDB"""



con.execute("""
    CREATE OR REPLACE TABLE gold_fraude_canal AS
    SELECT *
    FROM read_parquet(?)
""", [GOLD_CANAL_PATH])

con.execute("""
    CREATE OR REPLACE TABLE gold_fraude_categoria AS
    SELECT *
    FROM read_parquet(?)
""", [GOLD_CATEGORIA_PATH])

con.execute("""
    CREATE OR REPLACE TABLE gold_fraude_segmento AS
    SELECT *
    FROM read_parquet(?)
""", [gold_segmento_path])

con.execute("""
    CREATE OR REPLACE TABLE gold_fraude_periodo AS
    SELECT *
    FROM read_parquet(?)
""", [gold_periodo_path])

print("Tabelas Gold disponibilizadas no DuckDB.")

"""### Validar o Serving"""

print("=" * 70)
print("SERVING — DUCKDB")
print("=" * 70)

tabelas = con.execute(
    "SHOW TABLES"
).fetchdf()

display(tabelas)

"""### Consulta Gold por canal"""

resultado_canal = con.execute("""
    SELECT
        channel,
        total_transacoes,
        transacoes_fraudulentas,
        taxa_fraude,
        valor_total,
        valor_fraudado,
        risk_score_medio
    FROM gold_fraude_canal
    ORDER BY taxa_fraude DESC
""").fetchdf()

display(resultado_canal)

"""### Consulta Gold por categoria"""

resultado_categoria = con.execute("""
    SELECT
        merchant_category,
        total_transacoes,
        transacoes_fraudulentas,
        taxa_fraude,
        valor_total,
        valor_fraudado,
        risk_score_medio
    FROM gold_fraude_categoria
    ORDER BY taxa_fraude DESC
""").fetchdf()

display(resultado_categoria)

"""### Resumo final do pipeline"""

print("=" * 70)
print("RESUMO FINAL — PIPELINE TECHPAY")
print("=" * 70)

print(
    f"1. RAW:     {len(df_raw):,} linhas"
)

print(
    f"2. BRONZE:  {linhas_final_bronze:,} linhas"
)

print(
    f"3. SILVER:  {linhas_silver:,} linhas"
)

print(
    f"4. Gold - canal:      {len(gold_canal):,} registros"
)

print(
    f"5. Gold - categoria:  {len(gold_categoria):,} registros"
)

print(
    f"6. Gold - segmento:   {len(gold_segmento):,} registros"
)

print(
    f"7. Gold - período:    {len(gold_periodo):,} registros"
)

print()
print(
    f"Linhas descartadas na Bronze: "
    f"{linhas_descartadas:,}"
)

print()
print("Pipeline executado com sucesso.")

"""### Fechar o DuckDB"""

con.close()

print("Conexão DuckDB encerrada.")

"""### Conferir arquivos produzidos"""

import os

print("=" * 70)
print("ARQUIVOS PRODUZIDOS")
print("=" * 70)

for raiz, diretorios, arquivos in os.walk(DATA_DIR):

    nivel = raiz.replace(DATA_DIR, "").count(os.sep)

    indentacao = "    " * nivel

    print(f"{indentacao}{os.path.basename(raiz)}/")

    for arquivo in arquivos:

        print(
            f"{indentacao}    {arquivo}"
        )