# -*- coding: utf-8 -*-
"""Projeto_Big_Data_ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GeaZAQKO1AQ_o1QEnCFMTO71xOtQVfT

# TECHPAY - MODELO DE PREVISÃO DE FRAUDE
### Regressão Logística com PySpark ML
"""

from pyspark.sql import SparkSession
from pyspark.ml import Pipeline
from pyspark.ml.feature import (
    StringIndexer,
    OneHotEncoder,
    VectorAssembler
)
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.evaluation import (
    BinaryClassificationEvaluator,
    MulticlassClassificationEvaluator
)

import pandas as pd
import pyarrow.parquet as pq
import os
from google.colab import drive

"""### Spark"""

spark = (
    SparkSession.builder
    .appName("TechPay_Modelo_Fraude")
    .master("local[*]")
    .getOrCreate()
)

#Drive
drive.mount('/content/drive')

# 2. CARREGAR OS DADOS SILVER
# CORREÇÃO DO PARQUET PARA COMPATIBILIDADE COM PYSPARK

# Arquivo original
caminho_silver = (
    "/content/drive/MyDrive/"
    "avaliacao_final/etapa2_bigdata/"
    "data/silver/transactions_silver.parquet"
)

# Novo arquivo compatível com Spark
caminho_silver_spark = (
    "/content/drive/MyDrive/"
    "avaliacao_final/etapa2_bigdata/"
    "data/silver/transactions_silver_spark.parquet"
)

print("Lendo Parquet com Pandas/PyArrow...")

df_temp = pd.read_parquet(
    caminho_silver
)

print("Dados carregados.")
print("Linhas:", len(df_temp))

# ============================================================
# CONVERTER TIMESTAMP
# ============================================================

if "timestamp" in df_temp.columns:

    df_temp["timestamp"] = pd.to_datetime(
        df_temp["timestamp"]
    )

    df_temp["timestamp"] = (
        df_temp["timestamp"]
        .astype("datetime64[us]")
    )

    print("Timestamp convertido para microssegundos.")


# ============================================================
# SALVAR NOVO PARQUET
# ============================================================

df_temp.to_parquet(
    caminho_silver_spark,
    engine="pyarrow",
    index=False
)

print("\nNovo arquivo criado:")
print(caminho_silver_spark)


# ============================================================
# LER COM PYSPARK
# ============================================================

df = spark.read.parquet(
    caminho_silver_spark
)

print("\nDados carregados pelo Spark com sucesso!")

print("Quantidade de registros:", df.count())

df.printSchema()

# 3. SELECIONAR AS COLUNAS NECESSÁRIAS

colunas = [
    "transaction_id",
    "amount",
    "risk_score",
    "credit_score",
    "segment",
    "is_fraud"
]

df_ml = df.select(colunas)

print("\nColunas utilizadas no modelo:")
df_ml.printSchema()

# 4. VERIFICAR VALORES NULOS

print("\nValores nulos:")

for coluna in colunas:
    quantidade = df_ml.filter(
        df_ml[coluna].isNull()
    ).count()

    print(f"{coluna}: {quantidade}")

# 5. PREPARAR A VARIÁVEL TARGET

df_ml = df_ml.withColumn(
    "label",
    df_ml["is_fraud"].cast("double")
)

print("\nDistribuição da variável alvo:")

df_ml.groupBy("label").count().show()

# 6. PREPARAR A FEATURE CATEGÓRICA

# Transformar segment em índice numérico
segment_indexer = StringIndexer(
    inputCol="segment",
    outputCol="segment_idx",
    handleInvalid="keep"
)


# Transformar o índice em variáveis binárias
encoder = OneHotEncoder(
    inputCol="segment_idx",
    outputCol="segment_encoded"
)

# 7. MONTAR O VETOR DE FEATURES

assembler = VectorAssembler(
    inputCols=[
        "amount",
        "risk_score",
        "credit_score",
        "segment_encoded"
    ],
    outputCol="features"
)

# 8. REGRESSÃO LOGÍSTICA
# ============================================================

lr = LogisticRegression(
    featuresCol="features",
    labelCol="label",
    predictionCol="prediction",
    probabilityCol="probability",
    rawPredictionCol="rawPrediction"
)

# 9. MONTAR O PIPELINE

pipeline = Pipeline(
    stages=[
        segment_indexer,
        encoder,
        assembler,
        lr
    ]
)

# 10. DIVIDIR TREINO E TESTE
# ============================================================

train, test = df_ml.randomSplit(
    [0.8, 0.2],
    seed=42
)

print("\nDivisão dos dados:")
print(f"Treino: {train.count()} registros")
print(f"Teste:  {test.count()} registros")

# 11. TREINAR O MODELO

print("\nTreinando o modelo...")

modelo = pipeline.fit(train)

# 12. REALIZAR AS PREDIÇÕES

predicoes = modelo.transform(test)

print("\nExemplos de predições:")

predicoes.select(
    "transaction_id",
    "amount",
    "risk_score",
    "credit_score",
    "segment",
    "label",
    "prediction",
    "probability"
).show(
    10,
    truncate=False
)

# 13. AVALIAR AUC

avaliador_auc = BinaryClassificationEvaluator(
    labelCol="label",
    rawPredictionCol="rawPrediction",
    metricName="areaUnderROC"
)

auc = avaliador_auc.evaluate(predicoes)

print("\n" + "=" * 60)
print("AVALIAÇÃO DO MODELO")
print("=" * 60)

print(f"AUC: {auc:.4f}")

# 14. AVALIAR ACURÁCIA

avaliador_accuracy = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="accuracy"
)

accuracy = avaliador_accuracy.evaluate(predicoes)

print(f"Acurácia: {accuracy:.4f}")

# 15. PRECISÃO

avaliador_precision = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="weightedPrecision"
)

precision = avaliador_precision.evaluate(predicoes)

print(f"Precisão: {precision:.4f}")

# 16. RECALL
# ============================================================

avaliador_recall = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="weightedRecall"
)

recall = avaliador_recall.evaluate(predicoes)

print(f"Recall: {recall:.4f}")

# 17. F1-SCORE

avaliador_f1 = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="f1"
)

f1 = avaliador_f1.evaluate(predicoes)

print(f"F1-score: {f1:.4f}")

# 18. MATRIZ DE CONFUSÃO

print("\nMatriz de confusão:")

matriz_confusao = (
    predicoes
    .groupBy("label", "prediction")
    .count()
    .orderBy("label", "prediction")
)

matriz_confusao.show()

# 19. COEFICIENTES DA REGRESSÃO LOGÍSTICA

lr_model = modelo.stages[-1]

print("\n" + "=" * 60)
print("COEFICIENTES DO MODELO")
print("=" * 60)

print("\nCoeficientes:")
print(lr_model.coefficients)

print("\nIntercepto:")
print(lr_model.intercept)

# 20. INTERPRETAÇÃO DOS COEFICIENTES
# ============================================================

print("\nInterpretação:")

print(
    """
Coeficiente positivo:
    aumenta a tendência prevista para fraude.

Coeficiente negativo:
    reduz a tendência prevista para fraude.

Quanto maior o valor absoluto do coeficiente,
maior a influência da variável no modelo,
considerando a escala em que ela foi apresentada.
"""
)

# 21 EXTRAIR PROBABILIDADE DE FRAUDE

from pyspark.ml.functions import vector_to_array

predicoes_risco = predicoes.withColumn(
    "probabilidade_fraude",
    vector_to_array("probability")[1]
)

print("\nExemplos com probabilidade de fraude:")

predicoes_risco.select(
    "transaction_id",
    "amount",
    "risk_score",
    "credit_score",
    "segment",
    "probabilidade_fraude",
    "prediction"
).orderBy(
    "probabilidade_fraude",
    ascending=False
).show(
    20,
    truncate=False
)

# 22. SALVAR RESULTADOS

caminho_resultados = (
    "/content/drive/MyDrive/"
    "avaliacao_final/etapa3_analise/"
    "predicoes_fraude.parquet"
)

(
    predicoes_risco
    .select(
        "transaction_id",
        "amount",
        "risk_score",
        "credit_score",
        "segment",
        "label",
        "prediction",
        "probabilidade_fraude"
    )
    .write
    .mode("overwrite")
    .parquet(caminho_resultados)
)

print("\nPredições salvas em:")
print(caminho_resultados)

# 23. RESUMO FINAL
# ============================================================

print("\n" + "=" * 60)
print("RESUMO FINAL")
print("=" * 60)

print(f"Registros totais: {df_ml.count()}")
print(f"Registros de treino: {train.count()}")
print(f"Registros de teste: {test.count()}")
print(f"AUC: {auc:.4f}")
print(f"Acurácia: {accuracy:.4f}")
print(f"Precisão: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")

spark.stop()